// <auto-generated />
namespace SportClub.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _explicit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_explicit));
        
        string IMigrationMetadata.Id
        {
            get { return "202006041840390_explicit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
